# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\UI\УСДЗ\УСДЗ.ui'
#
# Created: Wed Dec 18 17:29:09 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_USDZ(object):
    def setupUi(self, USDZ):
        USDZ.setObjectName("USDZ")
        USDZ.resize(1540, 899)
        USDZ.setStyleSheet("background: rgb(213, 213, 213)")
        self.Edit = QtGui.QTabWidget(USDZ)
        self.Edit.setGeometry(QtCore.QRect(0, 0, 1581, 911))
        self.Edit.setStyleSheet("background: rgb(213, 213, 213)")
        self.Edit.setObjectName("Edit")
        self.New = QtGui.QWidget()
        self.New.setObjectName("New")
        self.Organization_Edit = QtGui.QLineEdit(self.New)
        self.Organization_Edit.setGeometry(QtCore.QRect(110, 20, 471, 21))
        self.Organization_Edit.setStyleSheet("background: rgb(255, 250, 250)")
        self.Organization_Edit.setText("")
        self.Organization_Edit.setObjectName("Organization_Edit")
        self.Address_Edit = QtGui.QLineEdit(self.New)
        self.Address_Edit.setGeometry(QtCore.QRect(150, 50, 511, 22))
        self.Address_Edit.setStyleSheet("background: rgb(255, 250, 250)")
        self.Address_Edit.setText("")
        self.Address_Edit.setObjectName("Address_Edit")
        self.INN_Edit = QtGui.QLineEdit(self.New)
        self.INN_Edit.setGeometry(QtCore.QRect(60, 80, 111, 22))
        self.INN_Edit.setStyleSheet("background: rgb(255, 250, 250)")
        self.INN_Edit.setText("")
        self.INN_Edit.setObjectName("INN_Edit")
        self.KPP_Edit = QtGui.QLineEdit(self.New)
        self.KPP_Edit.setGeometry(QtCore.QRect(220, 80, 111, 22))
        self.KPP_Edit.setStyleSheet("background: rgb(255, 250, 250)")
        self.KPP_Edit.setText("")
        self.KPP_Edit.setObjectName("KPP_Edit")
        self.F_I_O_Edit_Line1 = QtGui.QLineEdit(self.New)
        self.F_I_O_Edit_Line1.setGeometry(QtCore.QRect(20, 320, 461, 22))
        self.F_I_O_Edit_Line1.setStyleSheet("background: rgb(255, 250, 250)")
        self.F_I_O_Edit_Line1.setText("")
        self.F_I_O_Edit_Line1.setObjectName("F_I_O_Edit_Line1")
        self.Position_Edit_Line1 = QtGui.QLineEdit(self.New)
        self.Position_Edit_Line1.setGeometry(QtCore.QRect(500, 320, 331, 22))
        self.Position_Edit_Line1.setStyleSheet("background: rgb(255, 250, 250)")
        self.Position_Edit_Line1.setText("")
        self.Position_Edit_Line1.setObjectName("Position_Edit_Line1")
        self.Phone_Edit_Line1 = QtGui.QLineEdit(self.New)
        self.Phone_Edit_Line1.setGeometry(QtCore.QRect(850, 320, 121, 22))
        self.Phone_Edit_Line1.setStyleSheet("background: rgb(255, 250, 250)")
        self.Phone_Edit_Line1.setText("")
        self.Phone_Edit_Line1.setObjectName("Phone_Edit_Line1")
        self.In_the_face_Edit = QtGui.QLineEdit(self.New)
        self.In_the_face_Edit.setGeometry(QtCore.QRect(400, 80, 301, 22))
        self.In_the_face_Edit.setStyleSheet("background: rgb(255, 250, 250)")
        self.In_the_face_Edit.setText("")
        self.In_the_face_Edit.setObjectName("In_the_face_Edit")
        self.Based_Edit = QtGui.QLineEdit(self.New)
        self.Based_Edit.setGeometry(QtCore.QRect(820, 80, 271, 22))
        self.Based_Edit.setStyleSheet("background: rgb(255, 250, 250)")
        self.Based_Edit.setText("")
        self.Based_Edit.setObjectName("Based_Edit")
        self.INN = QtGui.QLabel(self.New)
        self.INN.setGeometry(QtCore.QRect(20, 80, 31, 16))
        self.INN.setObjectName("INN")
        self.KPP = QtGui.QLabel(self.New)
        self.KPP.setGeometry(QtCore.QRect(180, 80, 31, 16))
        self.KPP.setObjectName("KPP")
        self.in_the_face = QtGui.QLabel(self.New)
        self.in_the_face.setGeometry(QtCore.QRect(350, 80, 41, 16))
        self.in_the_face.setObjectName("in_the_face")
        self.F_I_O = QtGui.QLabel(self.New)
        self.F_I_O.setGeometry(QtCore.QRect(230, 300, 53, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.F_I_O.setFont(font)
        self.F_I_O.setObjectName("F_I_O")
        self.Position = QtGui.QLabel(self.New)
        self.Position.setGeometry(QtCore.QRect(620, 300, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Position.setFont(font)
        self.Position.setObjectName("Position")
        self.Based = QtGui.QLabel(self.New)
        self.Based.setGeometry(QtCore.QRect(730, 80, 81, 16))
        self.Based.setObjectName("Based")
        self.Organization = QtGui.QLabel(self.New)
        self.Organization.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.Organization.setObjectName("Organization")
        self.Address = QtGui.QLabel(self.New)
        self.Address.setGeometry(QtCore.QRect(20, 50, 131, 16))
        self.Address.setObjectName("Address")
        self.contact_details = QtGui.QLabel(self.New)
        self.contact_details.setGeometry(QtCore.QRect(240, 230, 811, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.contact_details.setFont(font)
        self.contact_details.setObjectName("contact_details")
        self.F_I_O_Edit_Line2 = QtGui.QLineEdit(self.New)
        self.F_I_O_Edit_Line2.setGeometry(QtCore.QRect(20, 380, 461, 22))
        self.F_I_O_Edit_Line2.setStyleSheet("background: rgb(255, 250, 250)")
        self.F_I_O_Edit_Line2.setText("")
        self.F_I_O_Edit_Line2.setObjectName("F_I_O_Edit_Line2")
        self.Position_Edit_Line2 = QtGui.QLineEdit(self.New)
        self.Position_Edit_Line2.setGeometry(QtCore.QRect(500, 380, 331, 22))
        self.Position_Edit_Line2.setStyleSheet("background: rgb(255, 250, 250)")
        self.Position_Edit_Line2.setText("")
        self.Position_Edit_Line2.setObjectName("Position_Edit_Line2")
        self.Phone_Edit_Line2 = QtGui.QLineEdit(self.New)
        self.Phone_Edit_Line2.setGeometry(QtCore.QRect(850, 380, 121, 22))
        self.Phone_Edit_Line2.setStyleSheet("background: rgb(255, 250, 250)")
        self.Phone_Edit_Line2.setText("")
        self.Phone_Edit_Line2.setObjectName("Phone_Edit_Line2")
        self.F_I_O_Edit_Line3 = QtGui.QLineEdit(self.New)
        self.F_I_O_Edit_Line3.setGeometry(QtCore.QRect(20, 440, 461, 22))
        self.F_I_O_Edit_Line3.setStyleSheet("background: rgb(255, 250, 250)")
        self.F_I_O_Edit_Line3.setText("")
        self.F_I_O_Edit_Line3.setObjectName("F_I_O_Edit_Line3")
        self.Position_Edit_Line3 = QtGui.QLineEdit(self.New)
        self.Position_Edit_Line3.setGeometry(QtCore.QRect(500, 440, 331, 22))
        self.Position_Edit_Line3.setStyleSheet("background: rgb(255, 250, 250)")
        self.Position_Edit_Line3.setText("")
        self.Position_Edit_Line3.setObjectName("Position_Edit_Line3")
        self.Phone_Edit_Line3 = QtGui.QLineEdit(self.New)
        self.Phone_Edit_Line3.setGeometry(QtCore.QRect(850, 440, 121, 22))
        self.Phone_Edit_Line3.setStyleSheet("background: rgb(255, 250, 250)")
        self.Phone_Edit_Line3.setText("")
        self.Phone_Edit_Line3.setObjectName("Phone_Edit_Line3")
        self.Email_Edit_Line1 = QtGui.QLineEdit(self.New)
        self.Email_Edit_Line1.setGeometry(QtCore.QRect(1000, 320, 141, 22))
        self.Email_Edit_Line1.setStyleSheet("background: rgb(255, 250, 250)")
        self.Email_Edit_Line1.setText("")
        self.Email_Edit_Line1.setObjectName("Email_Edit_Line1")
        self.Email_Edit_Line2 = QtGui.QLineEdit(self.New)
        self.Email_Edit_Line2.setGeometry(QtCore.QRect(1000, 380, 141, 22))
        self.Email_Edit_Line2.setStyleSheet("background: rgb(255, 250, 250)")
        self.Email_Edit_Line2.setText("")
        self.Email_Edit_Line2.setObjectName("Email_Edit_Line2")
        self.Email_Edit_Line3 = QtGui.QLineEdit(self.New)
        self.Email_Edit_Line3.setGeometry(QtCore.QRect(1000, 440, 141, 22))
        self.Email_Edit_Line3.setStyleSheet("background: rgb(255, 250, 250)")
        self.Email_Edit_Line3.setText("")
        self.Email_Edit_Line3.setObjectName("Email_Edit_Line3")
        self.Email = QtGui.QLabel(self.New)
        self.Email.setGeometry(QtCore.QRect(1050, 300, 53, 16))
        self.Email.setObjectName("Email")
        self.Phone_number = QtGui.QLabel(self.New)
        self.Phone_number.setGeometry(QtCore.QRect(880, 300, 53, 21))
        self.Phone_number.setObjectName("Phone_number")
        self.add_user = QtGui.QPushButton(self.New)
        self.add_user.setGeometry(QtCore.QRect(1340, 840, 90, 27))
        self.add_user.setStyleSheet("pushButton {\n"
"background-color: white;\n"
"width: 75px;\n"
"geight: 50px;\n"
"front-size: 12px;\n"
"front-weight: bold;\n"
"border: none;\n"
"text-align: center;\n"
"}")
        self.add_user.setObjectName("add_user")
        self.cancel_user = QtGui.QPushButton(self.New)
        self.cancel_user.setGeometry(QtCore.QRect(1440, 840, 90, 27))
        self.cancel_user.setStyleSheet("pushButton {\n"
"background-color: white;\n"
"width: 75px;\n"
"geight: 50px;\n"
"front-size: 12px;\n"
"front-weight: bold;\n"
"border: none;\n"
"text-align: center;\n"
"}")
        self.cancel_user.setObjectName("cancel_user")
        self.line = QtGui.QFrame(self.New)
        self.line.setGeometry(QtCore.QRect(10, 210, 1161, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.New)
        self.line_2.setGeometry(QtCore.QRect(1160, 220, 20, 251))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtGui.QFrame(self.New)
        self.line_3.setGeometry(QtCore.QRect(10, 460, 1161, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtGui.QFrame(self.New)
        self.line_4.setGeometry(QtCore.QRect(0, 220, 20, 251))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtGui.QFrame(self.New)
        self.line_5.setGeometry(QtCore.QRect(0, 10, 20, 101))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtGui.QFrame(self.New)
        self.line_6.setGeometry(QtCore.QRect(1100, 10, 20, 101))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtGui.QFrame(self.New)
        self.line_7.setGeometry(QtCore.QRect(10, 100, 1101, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtGui.QFrame(self.New)
        self.line_8.setGeometry(QtCore.QRect(10, 0, 1101, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.Edit.addTab(self.New, "")
        self.Edit_2 = QtGui.QWidget()
        self.Edit_2.setObjectName("Edit_2")
        self.label_13 = QtGui.QLabel(self.Edit_2)
        self.label_13.setGeometry(QtCore.QRect(20, 50, 131, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_5 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 20, 471, 21))
        self.lineEdit_5.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(60, 80, 111, 22))
        self.lineEdit_6.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(220, 80, 111, 22))
        self.lineEdit_7.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_16 = QtGui.QLabel(self.Edit_2)
        self.label_16.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_26 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_26.setGeometry(QtCore.QRect(820, 80, 271, 22))
        self.lineEdit_26.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_26.setText("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_28 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_28.setGeometry(QtCore.QRect(150, 50, 511, 22))
        self.lineEdit_28.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_28.setText("")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_35 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_35.setGeometry(QtCore.QRect(400, 80, 301, 22))
        self.lineEdit_35.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_35.setText("")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.label_32 = QtGui.QLabel(self.Edit_2)
        self.label_32.setGeometry(QtCore.QRect(180, 80, 31, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtGui.QLabel(self.Edit_2)
        self.label_33.setGeometry(QtCore.QRect(730, 80, 81, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtGui.QLabel(self.Edit_2)
        self.label_34.setGeometry(QtCore.QRect(350, 80, 41, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtGui.QLabel(self.Edit_2)
        self.label_35.setGeometry(QtCore.QRect(20, 80, 31, 16))
        self.label_35.setObjectName("label_35")
        self.line_9 = QtGui.QFrame(self.Edit_2)
        self.line_9.setGeometry(QtCore.QRect(10, 460, 1441, 20))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.lineEdit_22 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_22.setGeometry(QtCore.QRect(20, 440, 461, 22))
        self.lineEdit_22.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_14 = QtGui.QLabel(self.Edit_2)
        self.label_14.setGeometry(QtCore.QRect(230, 300, 53, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_24 = QtGui.QLabel(self.Edit_2)
        self.label_24.setGeometry(QtCore.QRect(880, 300, 53, 21))
        self.label_24.setObjectName("label_24")
        self.lineEdit_23 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_23.setGeometry(QtCore.QRect(1000, 320, 141, 22))
        self.lineEdit_23.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_24.setGeometry(QtCore.QRect(500, 320, 331, 22))
        self.lineEdit_24.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_24.setText("")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_25.setGeometry(QtCore.QRect(20, 320, 461, 22))
        self.lineEdit_25.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_25.setText("")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_27 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_27.setGeometry(QtCore.QRect(500, 440, 331, 22))
        self.lineEdit_27.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.line_10 = QtGui.QFrame(self.Edit_2)
        self.line_10.setGeometry(QtCore.QRect(1440, 220, 20, 251))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.lineEdit_29 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_29.setGeometry(QtCore.QRect(1000, 380, 141, 22))
        self.lineEdit_29.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_29.setText("")
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.line_11 = QtGui.QFrame(self.Edit_2)
        self.line_11.setGeometry(QtCore.QRect(10, 210, 1441, 20))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.lineEdit_30 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_30.setGeometry(QtCore.QRect(850, 320, 121, 22))
        self.lineEdit_30.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_30.setText("")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_31.setGeometry(QtCore.QRect(20, 380, 461, 22))
        self.lineEdit_31.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_31.setText("")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_32.setGeometry(QtCore.QRect(500, 380, 331, 22))
        self.lineEdit_32.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_32.setText("")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_33.setGeometry(QtCore.QRect(1000, 440, 141, 22))
        self.lineEdit_33.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_33.setText("")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.label_29 = QtGui.QLabel(self.Edit_2)
        self.label_29.setGeometry(QtCore.QRect(1050, 300, 53, 16))
        self.label_29.setObjectName("label_29")
        self.lineEdit_34 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_34.setGeometry(QtCore.QRect(850, 440, 121, 22))
        self.lineEdit_34.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_34.setText("")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.label_31 = QtGui.QLabel(self.Edit_2)
        self.label_31.setGeometry(QtCore.QRect(620, 300, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.line_12 = QtGui.QFrame(self.Edit_2)
        self.line_12.setGeometry(QtCore.QRect(0, 220, 20, 251))
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.lineEdit_36 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_36.setGeometry(QtCore.QRect(850, 380, 121, 22))
        self.lineEdit_36.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_36.setText("")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_178 = QtGui.QLabel(self.Edit_2)
        self.label_178.setGeometry(QtCore.QRect(240, 230, 811, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_178.setFont(font)
        self.label_178.setObjectName("label_178")
        self.label_179 = QtGui.QLabel(self.Edit_2)
        self.label_179.setGeometry(QtCore.QRect(1250, 300, 81, 20))
        self.label_179.setObjectName("label_179")
        self.lineEdit_37 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_37.setGeometry(QtCore.QRect(1170, 320, 251, 22))
        self.lineEdit_37.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_37.setText("")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_38.setGeometry(QtCore.QRect(1170, 380, 251, 22))
        self.lineEdit_38.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_38.setText("")
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtGui.QLineEdit(self.Edit_2)
        self.lineEdit_39.setGeometry(QtCore.QRect(1170, 440, 251, 22))
        self.lineEdit_39.setStyleSheet("background: rgb(255, 250, 250)")
        self.lineEdit_39.setText("")
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.add_3 = QtGui.QPushButton(self.Edit_2)
        self.add_3.setGeometry(QtCore.QRect(1340, 840, 90, 27))
        self.add_3.setStyleSheet("pushButton {\n"
"background-color: white;\n"
"width: 75px;\n"
"geight: 50px;\n"
"front-size: 12px;\n"
"front-weight: bold;\n"
"border: none;\n"
"text-align: center;\n"
"}")
        self.add_3.setObjectName("add_3")
        self.cancel_3 = QtGui.QPushButton(self.Edit_2)
        self.cancel_3.setGeometry(QtCore.QRect(1440, 840, 90, 27))
        self.cancel_3.setStyleSheet("pushButton {\n"
"background-color: white;\n"
"width: 75px;\n"
"geight: 50px;\n"
"front-size: 12px;\n"
"front-weight: bold;\n"
"border: none;\n"
"text-align: center;\n"
"}")
        self.cancel_3.setObjectName("cancel_3")
        self.line_13 = QtGui.QFrame(self.Edit_2)
        self.line_13.setGeometry(QtCore.QRect(0, 10, 16, 101))
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtGui.QFrame(self.Edit_2)
        self.line_14.setGeometry(QtCore.QRect(10, 100, 1101, 20))
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtGui.QFrame(self.Edit_2)
        self.line_15.setGeometry(QtCore.QRect(1100, 10, 20, 101))
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtGui.QFrame(self.Edit_2)
        self.line_16.setGeometry(QtCore.QRect(10, 0, 1101, 20))
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.Edit.addTab(self.Edit_2, "")
        self.Database = QtGui.QWidget()
        self.Database.setObjectName("Database")
        self.Add_Data = QtGui.QPushButton(self.Database)
        self.Add_Data.setGeometry(QtCore.QRect(0, 0, 90, 27))
        self.Add_Data.setObjectName("Add_Data")
        self.Edit_Data = QtGui.QPushButton(self.Database)
        self.Edit_Data.setGeometry(QtCore.QRect(220, 0, 101, 27))
        self.Edit_Data.setObjectName("Edit_Data")
        self.Export_World = QtGui.QPushButton(self.Database)
        self.Export_World.setGeometry(QtCore.QRect(320, 0, 111, 27))
        self.Export_World.setObjectName("Export_World")
        self.Export_Excel = QtGui.QPushButton(self.Database)
        self.Export_Excel.setGeometry(QtCore.QRect(430, 0, 111, 27))
        self.Export_Excel.setObjectName("Export_Excel")
        self.Save_Data = QtGui.QPushButton(self.Database)
        self.Save_Data.setGeometry(QtCore.QRect(1340, 850, 90, 27))
        self.Save_Data.setObjectName("Save_Data")
        self.Cancel_Data = QtGui.QPushButton(self.Database)
        self.Cancel_Data.setGeometry(QtCore.QRect(1430, 850, 90, 27))
        self.Cancel_Data.setObjectName("Cancel_Data")
        self.Import_Excel = QtGui.QPushButton(self.Database)
        self.Import_Excel.setGeometry(QtCore.QRect(540, 0, 90, 27))
        self.Import_Excel.setObjectName("Import_Excel")
        self.tableWidget = QtGui.QTableWidget(self.Database)
        self.tableWidget.setGeometry(QtCore.QRect(0, 30, 1541, 821))
        self.tableWidget.setStyleSheet("background: rgb(255, 250, 250)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(40)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(30, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(31, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(32, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(33, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(34, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(35, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(36, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(37, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(38, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(39, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.Add_Data_to_seminar = QtGui.QPushButton(self.Database)
        self.Add_Data_to_seminar.setGeometry(QtCore.QRect(90, 0, 131, 27))
        self.Add_Data_to_seminar.setObjectName("Add_Data_to_seminar")
        self.Edit.addTab(self.Database, "")
        self.Seminar = QtGui.QWidget()
        self.Seminar.setObjectName("Seminar")
        self.Add_Seminat = QtGui.QPushButton(self.Seminar)
        self.Add_Seminat.setGeometry(QtCore.QRect(0, 0, 90, 27))
        self.Add_Seminat.setObjectName("Add_Seminat")
        self.Edit_Seminar = QtGui.QPushButton(self.Seminar)
        self.Edit_Seminar.setGeometry(QtCore.QRect(90, 0, 101, 27))
        self.Edit_Seminar.setObjectName("Edit_Seminar")
        self.Export_Excel_Seminar = QtGui.QPushButton(self.Seminar)
        self.Export_Excel_Seminar.setGeometry(QtCore.QRect(190, 0, 121, 27))
        self.Export_Excel_Seminar.setObjectName("Export_Excel_Seminar")
        self.treeView = QtGui.QTreeView(self.Seminar)
        self.treeView.setGeometry(QtCore.QRect(0, 30, 1541, 851))
        self.treeView.setStyleSheet("background: rgb(255, 250, 250)")
        self.treeView.setObjectName("treeView")
        self.Edit.addTab(self.Seminar, "")

        self.retranslateUi(USDZ)
        self.Edit.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(USDZ)

    def retranslateUi(self, USDZ):
        USDZ.setWindowTitle(QtGui.QApplication.translate("USDZ", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.INN.setText(QtGui.QApplication.translate("USDZ", "ИНН", None, QtGui.QApplication.UnicodeUTF8))
        self.KPP.setText(QtGui.QApplication.translate("USDZ", "КПП", None, QtGui.QApplication.UnicodeUTF8))
        self.in_the_face.setText(QtGui.QApplication.translate("USDZ", "В лице", None, QtGui.QApplication.UnicodeUTF8))
        self.F_I_O.setText(QtGui.QApplication.translate("USDZ", "Ф.И.О.", None, QtGui.QApplication.UnicodeUTF8))
        self.Position.setText(QtGui.QApplication.translate("USDZ", "Должность", None, QtGui.QApplication.UnicodeUTF8))
        self.Based.setText(QtGui.QApplication.translate("USDZ", "На основании", None, QtGui.QApplication.UnicodeUTF8))
        self.Organization.setText(QtGui.QApplication.translate("USDZ", "Организация", None, QtGui.QApplication.UnicodeUTF8))
        self.Address.setText(QtGui.QApplication.translate("USDZ", "Юридический адрес", None, QtGui.QApplication.UnicodeUTF8))
        self.contact_details.setText(QtGui.QApplication.translate("USDZ", "               Контакты участников", None, QtGui.QApplication.UnicodeUTF8))
        self.Email.setText(QtGui.QApplication.translate("USDZ", "E-mail", None, QtGui.QApplication.UnicodeUTF8))
        self.Phone_number.setText(QtGui.QApplication.translate("USDZ", "Телефон", None, QtGui.QApplication.UnicodeUTF8))
        self.add_user.setText(QtGui.QApplication.translate("USDZ", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_user.setText(QtGui.QApplication.translate("USDZ", "Отмена", None, QtGui.QApplication.UnicodeUTF8))
        self.Edit.setTabText(self.Edit.indexOf(self.New), QtGui.QApplication.translate("USDZ", "Новый участник", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("USDZ", "Юридический адрес", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("USDZ", "Организация", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("USDZ", "КПП", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("USDZ", "На основании", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("USDZ", "В лице", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("USDZ", "ИНН", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("USDZ", "Ф.И.О.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("USDZ", "Телефон", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("USDZ", "E-mail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("USDZ", "Должность", None, QtGui.QApplication.UnicodeUTF8))
        self.label_178.setText(QtGui.QApplication.translate("USDZ", "               Контакты участников", None, QtGui.QApplication.UnicodeUTF8))
        self.label_179.setText(QtGui.QApplication.translate("USDZ", "Примечания", None, QtGui.QApplication.UnicodeUTF8))
        self.add_3.setText(QtGui.QApplication.translate("USDZ", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_3.setText(QtGui.QApplication.translate("USDZ", "Отмена", None, QtGui.QApplication.UnicodeUTF8))
        self.Edit.setTabText(self.Edit.indexOf(self.Edit_2), QtGui.QApplication.translate("USDZ", "Редактировать участника", None, QtGui.QApplication.UnicodeUTF8))
        self.Add_Data.setText(QtGui.QApplication.translate("USDZ", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.Edit_Data.setText(QtGui.QApplication.translate("USDZ", "Редактировать", None, QtGui.QApplication.UnicodeUTF8))
        self.Export_World.setText(QtGui.QApplication.translate("USDZ", "Экспорт в World", None, QtGui.QApplication.UnicodeUTF8))
        self.Export_Excel.setText(QtGui.QApplication.translate("USDZ", "Экспорт в Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.Save_Data.setText(QtGui.QApplication.translate("USDZ", "Сохранить", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancel_Data.setText(QtGui.QApplication.translate("USDZ", "Отмена", None, QtGui.QApplication.UnicodeUTF8))
        self.Import_Excel.setText(QtGui.QApplication.translate("USDZ", "Импорт Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("USDZ", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("USDZ", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("USDZ", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(3).setText(QtGui.QApplication.translate("USDZ", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(4).setText(QtGui.QApplication.translate("USDZ", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(5).setText(QtGui.QApplication.translate("USDZ", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(6).setText(QtGui.QApplication.translate("USDZ", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(7).setText(QtGui.QApplication.translate("USDZ", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(8).setText(QtGui.QApplication.translate("USDZ", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(9).setText(QtGui.QApplication.translate("USDZ", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(10).setText(QtGui.QApplication.translate("USDZ", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(11).setText(QtGui.QApplication.translate("USDZ", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(12).setText(QtGui.QApplication.translate("USDZ", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(13).setText(QtGui.QApplication.translate("USDZ", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(14).setText(QtGui.QApplication.translate("USDZ", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(15).setText(QtGui.QApplication.translate("USDZ", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(16).setText(QtGui.QApplication.translate("USDZ", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(17).setText(QtGui.QApplication.translate("USDZ", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(18).setText(QtGui.QApplication.translate("USDZ", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(19).setText(QtGui.QApplication.translate("USDZ", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(20).setText(QtGui.QApplication.translate("USDZ", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(21).setText(QtGui.QApplication.translate("USDZ", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(22).setText(QtGui.QApplication.translate("USDZ", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(23).setText(QtGui.QApplication.translate("USDZ", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(24).setText(QtGui.QApplication.translate("USDZ", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(25).setText(QtGui.QApplication.translate("USDZ", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(26).setText(QtGui.QApplication.translate("USDZ", "27", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(27).setText(QtGui.QApplication.translate("USDZ", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(28).setText(QtGui.QApplication.translate("USDZ", "29", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(29).setText(QtGui.QApplication.translate("USDZ", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(30).setText(QtGui.QApplication.translate("USDZ", "31", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(31).setText(QtGui.QApplication.translate("USDZ", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(32).setText(QtGui.QApplication.translate("USDZ", "33", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(33).setText(QtGui.QApplication.translate("USDZ", "34", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(34).setText(QtGui.QApplication.translate("USDZ", "35", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(35).setText(QtGui.QApplication.translate("USDZ", "36", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(36).setText(QtGui.QApplication.translate("USDZ", "37", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(37).setText(QtGui.QApplication.translate("USDZ", "38", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(38).setText(QtGui.QApplication.translate("USDZ", "39", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(39).setText(QtGui.QApplication.translate("USDZ", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("USDZ", "Организация", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("USDZ", "Адрес", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("USDZ", "ИНН", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("USDZ", "КПП", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("USDZ", "Ф.И.О.", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("USDZ", "В лице", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("USDZ", "На основании", None, QtGui.QApplication.UnicodeUTF8))
        self.Add_Data_to_seminar.setText(QtGui.QApplication.translate("USDZ", "Добавить в семинар", None, QtGui.QApplication.UnicodeUTF8))
        self.Edit.setTabText(self.Edit.indexOf(self.Database), QtGui.QApplication.translate("USDZ", "База Данных", None, QtGui.QApplication.UnicodeUTF8))
        self.Add_Seminat.setText(QtGui.QApplication.translate("USDZ", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.Edit_Seminar.setText(QtGui.QApplication.translate("USDZ", "Редактировать", None, QtGui.QApplication.UnicodeUTF8))
        self.Export_Excel_Seminar.setText(QtGui.QApplication.translate("USDZ", "Экспорт в Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.Edit.setTabText(self.Edit.indexOf(self.Seminar), QtGui.QApplication.translate("USDZ", "Семинары", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    USDZ = QtGui.QDialog()
    ui = Ui_USDZ()
    ui.setupUi(USDZ)
    USDZ.show()
    sys.exit(app.exec_())

